### ISSUE TITLE
need to decide how to handle directories versus files in deposits

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/uchicagoldr-toolsuite#23] opened 2016-04-22 21:24 UTC
Right now we have split abstract classes LDRItem and LDRDirectory where the former has write, read, open, close, exists, is_flo and the latter has getHierarchyInfo and exists methods. 

There is a proposal to re-merge these two sub-classes into one again and add an instantiate data attribute that holds a delegate that handles the precise details of writing something whether it is a directory or a file.

**Comment by bnbalsamo** [comment] 2016-04-25 16:10
A case for re-merging the classes as children of the same class:

So, while doing some unrelated research I stumbled across [this](http://markmail.org/message/4eqjxx73opiswfis) post by Linus in a mailing list having to do with git handling of directories. The specifics are not relevant to us (we should handle directories) but the part that stuck out to me was the following:

> When you track an empty file, you very 
> much track the _content_ of that file, and "empty" just happens to be a 
> very valid content.
> 
> But when you track a "directory", you don't actually track its content at 
> all, you track it's _existence_, which is a very very very different 
> thing. I hope you understand from the above what is so different.

In our use case it isn't the case that we only track "files" which "exist" (thus our .exists() method). What this made me realize is that directories are a special case, but still integrally related to a base LDRPath class. They behave very similarly to an empty file, except they need to be directories when serialized. For this reason I propose we return to a setup like...

```
LDRPath ---> LDRLocalFilePath
        |--> LDRLocalDirectoryPath
```

LDRLocalFilePath implements your standard .open(), .close(), .read(), .write(), .exists()

LDRLocalDirectoryPath implements _just_ .open(), which creates the directory, and .close() as `pass`. It's .read() and .write() raise NotImplemented().

This paradigm matches the method which appears to be the easiest for creating a blank file on disk in python ([SO Citation](http://stackoverflow.com/a/12654798)):

`open('$filename', 'a').close()`

I think this method preserves the idea that these things are arbitrary sources of bytes fairly cleanly, and the implementation abides by sticking as close to the built-in open() behavior as possible.

My only qualms with this is I think it only makes sense for leaf directories, and then we have to account for how every serialization _other_ than files on disk handles an empty organizational unit, but I think we have to live with that if we want to store empty directories as something other than just blank files without a file extension in other serializations. This may warrant some discussion about either something like an origin_serialization attribute on LDRItem (which I am not crazy about), or perhaps a syntax to abide by in ldr_names of our file system serialization classes, file:// and dir:// perhaps?

**Comment by bnbalsamo** [comment] 2016-04-25 16:38
A polar opposite solution has occurred to me, which involves a significant amount more abstraction and a little bit of overhead for the file based serialization, but which I think abides by the protocol more-so than the previous suggestion.

The organization of files on disk is entirely arbitrary from the point of the view of the Structure itself. SegmentStructures view themselves as entirely flat container objects, and MaterialSuite's only care about resolving locations as sources/receptacles for bytes, with no heed paid to that location relative to anything else.

We store the origin file layout, when the source is files on disk, for a single purpose: convenience when constructing the original conceptual layout.

I think the equivalent here in physical accessions is the difference between preserving the original layout of a desk and the contents of that desk. Except for in extreme cases it is not practical to accession a desk and the arrangement of papers on it as a single artifact, so the relative locations of the papers on a desk to each other and to the desk are disregarded during the accessioning process.

In the case where the ordering of papers on a desk may be important you could do something like take a picture of the original organization before destroying that positioning information. The digital equivalent of this picture could range from the addition to a .txt file specifying original layouts in a separate segment to zipping the entire structure + contents into a single file and calling that the artifact in question, to taking an iso of the source disk.

All of these solutions introduce a bit of overhead to remedy our issues with empty directories - but keeping in mind the physical metaphor, I now think a more practical way to handle this edge is case is exactly as any other edge case could be handled - by explicitly introducing a reproduction of implicit information which may be disregarded during handling of original file content as separate addressable, explicitly understood, information.

I briefly bounced this idea of Kathleen, and she agreed at the time that it seemed to be a reasonable solution to our issue.

**Comment by verbalhanglider** [comment] 2016-04-25 17:16
Response to bnbalsamo  first comment above:

Linus's suggestion about how to think about empty files vs directories is (I also think) very relevant to our problem here.  

But, the idea of merging LDRPathRegularDirectory and LDRPathRegularFile into subclasses of the same thing (LDRItem) but with with one just outright ignoring implementation of certain methods is I think a troubling design decision.

The immediate problem I foresee with this is that now we are forcing future implementors of other directory or file classes to know that in directory cases they have to define the required methods with but with a pass keyword in the body of the function.

Also: this doesn't really solve the problem of that directory and path are different but sort of the same.

**Comment by verbalhanglider** [comment] 2016-04-25 17:21
Response to bnbalsamo's second comment above:

I like this idea.

But, to get more clarification, does this mean we just have LDRPathRegularFile(LDRItem) and limit the staging directory as preserving only bytes. As a reference for future research we would capture a snapshot of the original directory structure, but we will not preserve the original directory structure.

The tasks required for this approach would include the following as far as I can tell:
1. create a directory in admin/ for each staging directory called something like "snapshot"
2. generate the snapshot of the directory structure
3. generate premis metadata for the snapshot file

**Comment by bnbalsamo** [comment] 2016-04-25 18:09
I think a case can be made for our default behavior to be disregarding storing directories as separate objects entirely. The fact that we use directories to store the serialized items in the case of LDRPath's is entirely up to the serializer/deserializer. I would also be opposed to introducing another StagingStructure level LDRItem to the protocol - I would instead propose we just generate this information on the fly when it is required and accession it as another segment of original data - potentially coming up with a way to delineate between "truly original" data and "archive created" data, but keeping all of it in the "data" portion of an accession rather than the administrative portion.

PREMIS description or some reserved Segment IDs seem to be the prime candidates for storing this information.

That keeps the implicit structural data that we've made explicit lumped with the data it describes, and accessible/controllable via the same mechanisms that will control access to the actual files it describes. Essentially these are presform files made from implicit information in the incoming data, rather than the explicit data contained in the files themselves.

It also means that we leave it up to the accessioner/archive to decide what information, if any, beyond the bytes are important in an accession, and how to save that information in an additional segment/segments.

Eg: 
Might some empty directories be of interest in here? Perhaps a segment including the ls -laR of each addressed location.

Is the structure almost assuredly important enough to warrant keeping a copy in the original order? Do we consider .tar.gz to be a preservation format? Save a zipped version as a standalone file for each addressed location.

Is the structure exceptionally important, or do we not think that any compression/zipping is preservation stable? Accession a directory full of iso's of the origin location in addition to their file contents pulled out.

**Comment by verbalhanglider** [comment] 2016-04-26 15:54
I think you're onto something with the example of a segment with an ls -laR output for staging directories that can be deemed that it's important to.

That segment could have a controlled identifier: something like originalStructureSnapshot that the serializer for the staging directory would then know to put that into an admin/snapshot directory.

This snapshot directory would then be optional and might be placed into a premis record.

But, this brings up another issue: what premis record does this kind of information belong to? Should we be creating a premis record for the staging directory itself that becomes the accession when it arrives in the archive directory?

**Comment by bnbalsamo** [comment] 2016-04-26 19:55
I don't think the output of the ls -laR in this case should be treated any differently (technically) then originating data. It's an implicit aspect of the data made explicit in this case. I think we are toe-ing the line where the digital space diverges significantly enough from the physical space that we have to set our own precedent here. 

"Explicit"-izing data, as we are doing here, is (I think) different from producing supplementary information that might be stored in metadata. In physical accessions I think this is the equivalent of introducing a photo of the original material organization into an additional box inserted into the collection specifically for the purpose of documenting original order. This data should be treated exactly the same as the data it is derived from, not flagged for inclusion in the admin data.

I think we might flag the difference between actual originating data and derived "explicit"-ized data in the PREMIS itself, and that PREMIS can still be created at the file level as we are doing now (because it would be describing a file we inserted into the accession). I think this kind of thing could warrant inclusion in the "significantProperties" element.

In regards to producing PREMIS for our organizational units (I think this is generalizable to stuff outside of staging directories): I think that might be a goal for the future - producing controlled vocabularies and implementation details for just the file level is proving to be a fair bit of work, once that is entirely hammered out I think we might work towards utilizing the more abstract PREMIS object types to model our organizational units.

**Comment by verbalhanglider** [comment] 2016-04-26 20:53
So, if I'm understanding correctly, than we should do the following:
1. mandate that part of staging from origin includes doing an ls -laR of the origin and sending the contents of that command to a file
2. mandate that this file be added to the stager directory being created as a new segment
3. accession this file like any other file in the staging directory
4. add a link to this fille somewhere in the accession record
5. archive this file as just like any other file in that staging directory

**Comment by bnbalsamo** [comment] 2016-04-26 21:03
> mandate that part of staging from origin includes doing an ls -laR of the origin and sending the contents of that command to a file

I wouldn't go so far as to say "mandate." The physical equivalent here (the picture of the desk) isn't the default behavior in a physical accession, just an option if a portion of the original structure that should be preserved is unavoidably destroyed during the process of accessioning. I just think the option to do something like this (and a formalization for the procedure) should be in place

> add a link to this file somewhere in the accession record

I don't think this is required. I think this file (and any file that serves the same role in the future) should be documented in it's file level PREMIS. In the future there may be a case where we generate hundreds of these for different purposes, or some such, this information isn't technically accession level, it's related to that data file in the accession.

**Closed as completed** 2016-08-08 16:09 UTC
Labels: question
